name: 'Repository-crawler'
description: 'Crawl organization repositories for innersourcing repos'
inputs:
  gh_token:  # github token
    description: 'Github token'
    required: true
  organization:  # github org
    description: 'Github organization'
    required: true 
  topic: # github topic
    description: 'Github topic to filter on'
    required: true
    default: 'inner-source'
  outputFilename:
    description: 'File to write the list to (json)'
    required: false
    default: 'repositories.json'
outputs:
  repositories: 
    description: 'The list of repositories'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
     - ${{ inputs.gh_token }}
     - ${{ inputs.organization }}
     - ${{ inputs.topic }}
     - ${{ inputs.outputFilename }}